#!/usr/bin/env bash
# This script configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80 and
# Serves a page that would return a Hello World string
sudo apt-get  update -y
sudo apt-get install nginx -y

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Creating new index
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Starting nginx
sudo service nginx start
